export const order = [
    {
      id: "0",
      day: "24/08/2020",
      technician: "Dr. John Smith",
      product: "Pacemaker",
      hospital: "NYU Langone Medical Center",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "1",
      day: "25/08/2020",
      technician: "Dr. Jane Doe",
      product: "Stethoscope",
      hospital: "Cleveland Clinic",
      status: "Progresso",
      priority: "Alta",
    },
    {
      id: "2",
      day: "26/08/2020",
      technician: "Dr. Robert Johnson",
      product: "MRI Scanner",
      hospital: "Massachusetts General Hospital",
      status: "Progresso",
      priority: "Média",
    },
    {
      id: "3",
      day: "27/08/2020",
      technician: "Dr. Lisa Davis",
      product: "Defibrillator",
      hospital: "Johns Hopkins Hospital",
      status: "Progresso",
      priority: "Alta",
    },
    {
      id: "4",
      day: "28/08/2020",
      technician: "Dr. Michael Brown",
      product: "Blood Pressure Monitor",
      hospital: "Mayo Clinic",
      status: "Progresso",
      priority: "Baixa",
    },
    {
      id: "5",
      day: "29/08/2020",
      technician: "Dr. Jennifer Miller",
      product: "Ultrasound Machine",
      hospital: "Stanford Health Care",
      status: "Concluido",
      priority: "Média",
    },
    {
      id: "6",
      day: "30/08/2020",
      technician: "Dr. William Wilson",
      product: "X-Ray Machine",
      hospital: "UCLA Medical Center",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "7",
      day: "31/08/2020",
      technician: "Dr. Emily Taylor",
      product: "ECG Machine",
      hospital: "Mount Sinai Hospital",
      status: "Progresso",
      priority: "Baixa",
    },
    {
      id: "8",
      day: "01/09/2020",
      technician: "Dr. Alice Turner",
      product: "Ventilator",
      hospital: "Houston Methodist Hospital",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "9",
      day: "02/09/2020",
      technician: "Dr. Carlos Martinez",
      product: "CT Scanner",
      hospital: "Cedars-Sinai Medical Center",
      status: "Progresso",
      priority: "Alta",
    },
    {
      id: "10",
      day: "03/09/2020",
      technician: "Dr. Sophia Johnson",
      product: "ECG Machine",
      hospital: "NewYork-Presbyterian Hospital",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "11",
      day: "04/09/2020",
      technician: "Dr. George Harris",
      product: "Pacemaker",
      hospital: "Massachusetts General Hospital",
      status: "Progresso",
      priority: "Média",
    },
    {
      id: "12",
      day: "05/09/2020",
      technician: "Dr. Olivia Lee",
      product: "X-Ray Machine",
      hospital: "UCSF Medical Center",
      status: "Concluido",
      priority: "Urgente",
    },
    {
      id: "13",
      day: "06/09/2020",
      technician: "Dr. Benjamin Moore",
      product: "Ultrasound Machine",
      hospital: "Cleveland Clinic",
      status: "Progresso",
      priority: "Alta",
    },
    {
      id: "14",
      day: "07/09/2020",
      technician: "Dr. Lily Thompson",
      product: "Defibrillator",
      hospital: "Mount Sinai Hospital",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "15",
      day: "08/09/2020",
      technician: "Dr. Ethan Wilson",
      product: "MRI Scanner",
      hospital: "Johns Hopkins Hospital",
      status: "Progresso",
      priority: "Alta",
    },
    {
      id: "16",
      day: "09/09/2020",
      technician: "Dr. Chloe Evans",
      product: "Stethoscope",
      hospital: "Mayo Clinic",
      status: "Progresso",
      priority: "Baixa",
    },
    {
      id: "17",
      day: "10/09/2020",
      technician: "Dr. Mason Green",
      product: "Blood Pressure Monitor",
      hospital: "NYU Langone Medical Center",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "18",
      day: "11/09/2020",
      technician: "Dr. Ella Davis",
      product: "Ventilator",
      hospital: "Stanford Health Care",
      status: "Progresso",
      priority: "Urgente",
    },
    {
      id: "19",
      day: "12/09/2020",
      technician: "Dr. Noah Hall",
      product: "CT Scanner",
      hospital: "Houston Methodist Hospital",
      status: "Concluido",
      priority: "Média",
    },
    {
      id: "20",
      day: "13/09/2020",
      technician: "Dr. Ava Martinez",
      product: "ECG Machine",
      hospital: "Cedars-Sinai Medical Center",
      status: "Progresso",
      priority: "Baixa",
    },
    {
        id: "21",
        day: "15/01/2024",
        technician: "Dr. Lucas Brown",
        product: "Ultrasound Machine",
        hospital: "NYU Langone Medical Center",
        status: "Progresso",
        priority: "Alta",
      },
      {
        id: "22",
        day: "20/02/2024",
        technician: "Dr. Mia Johnson",
        product: "Defibrillator",
        hospital: "Cleveland Clinic",
        status: "Concluido",
        priority: "Média",
      },
      {
        id: "23",
        day: "10/03/2024",
        technician: "Dr. Oliver Wilson",
        product: "Ventilator",
        hospital: "Massachusetts General Hospital",
        status: "Progresso",
        priority: "Urgente",
      },
      {
        id: "24",
        day: "25/04/2024",
        technician: "Dr. Amelia Davis",
        product: "ECG Machine",
        hospital: "Johns Hopkins Hospital",
        status: "Concluido",
        priority: "Baixa",
      },
      {
        id: "25",
        day: "15/05/2024",
        technician: "Dr. Liam Martinez",
        product: "Pacemaker",
        hospital: "Mayo Clinic",
        status: "Progresso",
        priority: "Alta",
      },
      {
        id: "26",
        day: "05/06/2024",
        technician: "Dr. Sophia Taylor",
        product: "MRI Scanner",
        hospital: "Stanford Health Care",
        status: "Concluido",
        priority: "Urgente",
      },
      {
        id: "27",
        day: "18/07/2024",
        technician: "Dr. Elijah Lee",
        product: "X-Ray Machine",
        hospital: "Mount Sinai Hospital",
        status: "Progresso",
        priority: "Baixa",
      },
      {
        id: "28",
        day: "09/08/2024",
        technician: "Dr. Harper Harris",
        product: "Blood Pressure Monitor",
        hospital: "Cedars-Sinai Medical Center",
        status: "Progresso",
        priority: "Média",
      },
      {
        id: "29",
        day: "14/09/2024",
        technician: "Dr. James Moore",
        product: "Stethoscope",
        hospital: "UCSF Medical Center",
        status: "Concluido",
        priority: "Alta",
      },
      {
        id: "30",
        day: "21/10/2024",
        technician: "Dr. Evelyn Martinez",
        product: "CT Scanner",
        hospital: "Houston Methodist Hospital",
        status: "Progresso",
        priority: "Urgente",
      }
  ]